<?php include 'inc/header.phtml'; ?>
<?php include 'inc/funkcie.php'; ?>


<div class="container-fluid carousel-edit mt-2">
	<a  class="btn btn-primary m-2" href="<?php echo $baseurl; ?>/admin/carousel/new">Nový</a>
	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>header</th>
			<th>content</th>
			<th>img</th>
			<th>dobchod</th>
			<th>trailer</th>
			<th>Akcia</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach ($carousel as $row) {
						
		?>
		
		<tr>
			<td><?php echo $row['id'] ?></td>
			<td><?php echo $row['header'] ?></td>
			<td><?php echo short($row['content'] , 30); ?></td>
			<td><img  src="<?php echo $baseurl."/img/carousel/".$row["img_name"]; ?>" alt=""></td>
			<td><?php echo short($row['obchod'], 30) ?></td>
			<td><?php echo short($row['trailer'], 30) ?></td>
			<td>
			<a class="btn btn-success" href="<?php echo $baseurl; ?>/admin/carousel/edit/<?php echo $row['id']; ?>">Edit</a>
			<a data-toggle="modal" data-target="#myModal2/<?php echo $row['id']; ?>" class="btn btn-danger" >Delete</a>

			<div class="modal " id="myModal2/<?php echo $row['id']; ?>">
		  <div class="modal-dialog">
		    <div class="modal-content">

		      <!-- Modal Header -->
		      <div class="modal-header bg-dark">
		        <h4 class="modal-title">Upozornenie</h4>
		        <button type="button" class="close" data-dismiss="modal" style="color: white;">&times;</button>
		      </div>

		      <!-- Modal body -->
		      <div class="modal-body bg-dark">
		        Naozaj chcete vymazať prvok?
		      </div>

		      <!-- Modal footer -->
		      <div class="modal-footer bg-dark">
		        <button type="button" class="btn btn-primary" data-dismiss="modal">CLOSE</button>
		        <a type="button" class="btn btn-danger" href="<?php echo $baseurl; ?>/admin/carousel/delete/<?php echo $row['id']; ?>">DELETE</a>
		      </div>

		    </div>
		  </div>
		</div>
			</td>

		</tr>
		
<?php 
		}
?>


	</tbody>
</table>
</div>
<?php include 'inc/footer.phtml'; ?>