<?php include 'inc/header.phtml'; ?>
<div class="container">
	<?php $row = (isset($recenzie[0]) ? $recenzie[0] : ''); ?>

	<form action="<?php echo $baseurl; ?>/admin/recenzie/save/<?php echo (isset($recenzie[0]) ? $row['id'] : ''); ?>" method="post" enctype="multipart/form-data">

	<input type="hidden" name="id" value="<?php echo (isset($recenzie[0]) ? $row['id'] : '');  ?>"><br>

	
	<label>Nadpis</label>
	<input type="text" class="form-control" name="header" value="<?php echo (isset($recenzie[0]) ? $row['header'] : ''); ?>"><br>
	
	<label>Obsah</label>
	<textarea name="content" id="editor1" cols="20" rows="15"><?php echo (isset($recenzie[0]) ? $row['main_content'] : '');  ?></textarea><br>

	<label>Hodnotenie</label>
	<input type="text" class="form-control" name="hodnotenie" value="<?php echo (isset($recenzie[0]) ? $row['hodnotenie'] : ''); ?>"><br>

	<label>Obchod</label>
	<input type="text" class="form-control" name="obchod" value="<?php echo (isset($recenzie[0]) ? $row['obchod'] : ''); ?>"><br>

	<label>Recenzia</label>
	<input type="text" class="form-control" name="trailer" value="<?php echo (isset($recenzie[0]) ? $row['trailer'] : ''); ?>"><br>
	
	<label>Mala fotka - viacero recenzií (620*390)</label>
	<input type="file" name="img" class="form-control">

	<label>Veľká fotka - hlavná recenzia (1920*650)</label>
	<input type="file" name="main_img" class="form-control">

	<input class="btn btn-danger mt-2" type="submit" value="Poslať">

</form>
</div>
<?php include 'inc/footer.phtml'; ?>