<?php include 'inc/header.phtml'; ?>
<?php include 'inc/funkcie.php'; ?>

<div class="container-fluid  mt-2">
	<a  class="btn btn-primary m-2" href="<?php echo $baseurl; ?>/admin/recenzie/new">Nový</a>
	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>header</th>
			<th>content</th>
			<th>mala_img</th>
			<th>main_img</th>
			<th>hodnotenie</th>
			<th>obchod</th>
			<th>trailer</th>
			<th>akcia</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach ($recenzie as $row) {
						
		?>
		
		<tr>
			<td><?php echo $row['id'] ?></td>
			<td><?php echo $row['header'] ?></td>
			<td><?php echo short($row['main_content'], 35); ?></td>
			
			<td><img class="n_mala_img" src="<?php echo $baseurl."/img/hry/".$row["img_mala"]; ?>" alt=""></td>
			<td><img class="n_main_img" src="<?php echo $baseurl."/img/hry/".$row["img_velka"]; ?>" alt=""></td>
			<td><?php echo $row['hodnotenie'] ?></td>
			<td><?php echo short($row['obchod'], 35); ?></td>
			<td><?php echo short($row['trailer'], 35); ?></td>
			<td>
			<a class="btn btn-success" href="<?php echo $baseurl; ?>/admin/recenzie/edit/<?php echo $row['id']; ?>">Edit</a>
			<a data-toggle="modal" data-target="#myModal3/<?php echo $row['id']; ?>" class="btn btn-danger" >Delete</a>

			<div class="modal " id="myModal3/<?php echo $row['id']; ?>">
		  <div class="modal-dialog">
		    <div class="modal-content">

		      <!-- Modal Header -->
		      <div class="modal-header bg-dark">
		        <h4 class="modal-title">Upozornenie</h4>
		        <button type="button" class="close" data-dismiss="modal" style="color: white;">&times;</button>
		      </div>

		      <!-- Modal body -->
		      <div class="modal-body bg-dark">
		        Naozaj chcete vymazať prvok?
		      </div>

		      <!-- Modal footer -->
		      <div class="modal-footer bg-dark">
		        <button type="button" class="btn btn-primary" data-dismiss="modal">CLOSE</button>
		        <a type="button" class="btn btn-danger" href="<?php echo $baseurl; ?>/admin/recenzie/delete/<?php echo $row['id']; ?>">DELETE</a>
		      </div>

		    </div>
		  </div>
		</div>
			</td>

		</tr>
		
<?php 
		}
?>


	</tbody>
</table>
</div>

<?php include 'inc/footer.phtml'; ?>