<?php include 'inc/header.phtml' ?>
<?php include 'inc/funkcie.php'; ?>

<div class="container-fluid  mt-2">
	<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>komentar</th>
			<th>akcia</th>
		</tr>
	</thead>
	<tbody>
		<?php 
			foreach ($topics as $row) {
						
		?>
		
		<tr>
			<td><?php echo $row['id'] ?></td>
			<td><?php echo short($row['answer'], 60); ?></td>
			<td>
			<a class="btn btn-success" href="<?php echo $baseurl; ?>/admin/komentare/edit/<?php echo $row['id']; ?>">Edit</a>
			<a data-toggle="modal" data-target="#myModal4/<?php echo $row['id']; ?>" class="btn btn-danger" >Delete</a>

			<div class="modal " id="myModal4/<?php echo $row['id']; ?>">
		  <div class="modal-dialog">
		    <div class="modal-content">

		      <!-- Modal Header -->
		      <div class="modal-header bg-dark">
		        <h4 class="modal-title">Upozornenie</h4>
		        <button type="button" class="close" data-dismiss="modal" style="color: white;">&times;</button>
		      </div>

		      <!-- Modal body -->
		      <div class="modal-body bg-dark">
		        Naozaj chcete vymazať prvok?
		      </div>

		      <!-- Modal footer -->
		      <div class="modal-footer bg-dark">
		        <button type="button" class="btn btn-primary" data-dismiss="modal">CLOSE</button>
		        <a type="button" class="btn btn-danger" href="<?php echo $baseurl; ?>/admin/komentare/delete/<?php echo $row['id']; ?>">DELETE</a>
		      </div>

		    </div>
		  </div>
		</div>
			</td>

		</tr>
		
<?php 
		}
?>


	</tbody>
</table>
</div>

<?php include 'inc/footer.phtml' ?>