<div class="container-fluid cele_new_release mt-2">
	<div class="row">
		<div class="col-12">
			<h3 class="ml-5">Najnovšie fóra</h3>
		</div>
	</div>
</div>
<div class="container">
	
	<div class="row">
		<?php 
			foreach ($forum as $value){
				?>
				<?php  
				$time = strtotime($value['date_c']);
				$myFormatForView = date("d-m-Y H:i:s", $time);
		?>

		<?php  
					$string = strip_tags($value['popis']);
					if (strlen($string) > 200) {

					    // truncate string
					    $stringCut = substr($string, 0, 200);
					    $endPoint = strrpos($stringCut, ' ');

					    //if the string doesn't contain any space then it will cut without word basis.
					    $string = $endPoint? substr($stringCut, 0, $endPoint) : substr($stringCut, 0);
					    $string .= '...';
					}
					
		?>

			<div class="col-md-4 mb-4">
				<h5 class="hvr-grow"><a style="color:#1a1b1e;" class="topic" href="<?php echo $baseurl; ?>/forum/<?php echo $value['id']; ?>"><span style="color: #b23939;">|</span> <?php echo $value['header']; ?></a></h5>
				<div class="hvr-shrink"><?php echo $string; ?></div>
			</div>
		<?php 

			}
	 		?>
	</div>
</div>