<div class="horizontal-slide">	
<div class="container-fluid cele_new_release pl-5">
	<h3>Nové vydania</h3>
</div>
<div class="container-fluid  animated wow slideInRight">
	<div class="row">
		<div class="col-12 new_r">
	<?php 
			foreach ($new_r as $value){
				$time = strtotime($value['date_c']);
				$myFormatForView = date("d-m-Y", $time);
				?>
	<div class="card mb-3 bg-light j-release hvr-shrink" style="max-width: 540px;">
	  <div class="row no-gutters">
	    <div class="col-md-4">
	      <img src="<?php echo $baseurl."/img/new_r/".$value["img"]; ?>" class="card-img" alt="...">
	    </div>
	    <div class="col-md-8">
	      <div class="card-body">
	        <h5 class="card-title"><?php echo $value['header']; ?></h5>
	        
	        <p class="card-text">Vydanie: <span class="vydanie"><?php echo $myFormatForView; ?></span></p>
	      </div>
	    </div>
	  </div>
	</div>
	<?php 

			}
	 		?>
	 	</div>
	</div>
</div>
</div>