<?php include 'inc/header.phtml' ?>

<div class="container novinky">
<div id="result"></div>	
	
	<?php 
			foreach ($new_r as $value){
				?>
				<?php  
				$time = strtotime($value['date_c']);
				$myFormatForView = date("d-m-Y H:i:s", $time);
				?>

				<?php  
					$string = strip_tags($value['main_content']);
					if (strlen($string) > 500) {

					    // truncate string
					    $stringCut = substr($string, 0, 500);
					    $endPoint = strrpos($stringCut, ' ');

					    //if the string doesn't contain any space then it will cut without word basis.
					    $string = $endPoint? substr($stringCut, 0, $endPoint) : substr($stringCut, 0);
					    $string .= '...';
					}
					
				?>
				
<div class="row">
	<div class="col-12 animated slideInUp">
	<div class="card mb-3 bg-dark" style="">
		  <div class="row no-gutters">
		    <div class="col-md-3 novinky_img">
		      <img src="<?php echo $baseurl."/img/novinky/".$value["img"]; ?>" class="card-img hvr-hang" alt="...">
		    </div>
		    <div class="col-md-9">
		      <div class="card-body">
		        <a class="nadpis_novinka hvr-grow" href="<?php echo $baseurl; ?>/novinky/<?php echo $value['id']; ?>"><?php echo $value['header']; ?></a>
		        
		        <p class="card-text "><small class="text-muted hvr-grow">Publikované: <?php echo $myFormatForView; ?></small></p>
		        <div><?php echo $string ?></div>

			        <?php if (strlen($string) > 400) { ?>
			        <div><a style="font-family: 'blocktasticregular';" href="<?php echo $baseurl; ?>/novinky/<?php echo $value['id']; ?>">Read more</a></div>
			        <?php 
					}
		 			?>

		      </div>
		    </div>

		  </div>
		</div>	
	</div>
</div>
	<?php 

			}
	 		?>	
</div>	

<div class="row justify-content-center p-0 m-0">
	<ul class="pager">
		<?php 

			for($i = 1;$i <= $cnt; $i++)
			{

		?>		

			<a class="paging_buton" href=" <?php echo $baseurl; ?>/novinky/?page=<?php echo $i; ?>"><li class="btn btn-lg bg-dark "><?php echo $i; ?></li></a>

		<?php

			}	

		  ?>
	</ul>
</div>

<?php include 'inc/footer.phtml' ?>
