<?php include 'inc/header.phtml' ?>
<div class="container mt-2 mb-0 pb-0">
 
			  <form action="" method="get">
			  <input type="text" placeholder="Vyhľadávanie" class="form-control" name="keyw" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default">
			  </form>
			

</div>
<div class="container novinky animated slideInLeft">
	
	
	<?php 
			foreach ($game as $value){
				?>
				<?php  
				$time = strtotime($value['date_c']);
				$myFormatForView = date("d-m-Y", $time);
				?>

				<?php  
					$string = strip_tags($value['main_content']);
					if (strlen($string) > 200) {

					    // truncate string
					    $stringCut = substr($string, 0, 200);
					    $endPoint = strrpos($stringCut, ' ');

					    //if the string doesn't contain any space then it will cut without word basis.
					    $string = $endPoint? substr($stringCut, 0, $endPoint) : substr($stringCut, 0);
					    $string .= '...';
					}
					
				?>
<div class="row">
	<div class="col-12">
	<div class="card mb-3 bg-dark" style="">
		  <div class="row no-gutters">
		    <div class="col-md-4">
		      <img src="<?php echo $baseurl."/img/hry/".$value["img_mala"]; ?>" class="card-img hvr-grow" alt="...">
		      

		    </div>
		    <div class="col-md-8">
		      <div class="card-body">
		        <a class="nadpis_recenzia hvr-grow" href="<?php echo $baseurl; ?>/recenzie/<?php echo $value['id']; ?>"><?php echo $value['header']; ?></a>
		        
		        <p class="card-text ">Publikované: <?php echo $myFormatForView; ?> ||<span class="h_size "> <?php echo $value['hodnotenie']; ?></span>/10</p>
		        <div><?php echo $string ?></div>

			        <?php if (strlen($string) > 100) { ?>
			        <div><a style="font-family: 'hackedregular';" href="<?php echo $baseurl; ?>/recenzie/<?php echo $value['id']; ?>">Read more</a></div>
			        <?php 
					}
		 			?>

		      </div>
		    </div>
		    
		  </div>
		</div>	
	</div>
</div>
	<?php 

			}
	 		?>	
</div>
<div class="row justify-content-center p-0 m-0">
	<ul class="pager">
		<?php 

			for($i = 1;$i <= $cnt; $i++)
			{

		?>		

			<a class="paging_buton hvr-rotate" href=" <?php echo $baseurl; ?>/recenzie/?page=<?php echo $i; ?>"><li class="btn btn-lg bg-dark "><?php echo $i; ?></li></a>

		<?php

			}	

		  ?>
	</ul>
</div>

<?php include 'inc/footer.phtml' ?>