<?php include 'inc/header.phtml' ?>
<div class="container mt-2">
	<div class="row ">
		<div class="col-3"></div>
		<div class="col-6 bg-dark">
			<div class="log_in">Registrácia</div>
			<form class="px-4 py-3" action="<?php echo $baseurl; ?>/registracia" method="post" enctype="multipart/form-data">
				<div><?php echo (isset($chyba) ? $chyba : ''); ?></div>
				<div><?php echo (isset($chyba_e) ? $chyba_e : ''); ?></div>
				<label>Meno/Nick</label>
				<input type="text" class="form-control" name="meno" placeholder="nick" value=""><br>
				
				<label>Heslo</label>
				<input type="password" class="form-control" name="heslo" placeholder="*****" value=""><br>
				<label>Uživateľske foto (50x50px)</label>
				<input type="file" name="img" class="form-control">
				<input type="submit" class="btn btn-outline-danger mt-2" value="Zaregistrovať sa">

			</form>
		</div>
		<div class="col-3"></div>
	</div>
</div>
<?php include 'inc/footer.phtml' ?>