<?php include 'inc/header.phtml' ?>
<?php //var_dump($topic);
//exit(); ?>
<div class="container bg-dark mt-2 pt-2">

		<?php 
        foreach ($topic as $value) 
		{
			$time = strtotime($value['date_c']);
			$myFormatForView = date("d-m-Y H:i:s", $time);
       	?>
			<div class="row">
				<div class="col-12">
					<div class="topic"><span style="color: #b23939;">|</span> <?php echo $value['header']; ?> 
					<span class="user_meno"><?php echo $value['meno']; ?></span>
					<img class="user_img_forum hvr-grow" src="<?php echo $baseurl."/img/users/".$value["img"]; ?>" alt="">
					</div>
					<div class="time"><?php echo $myFormatForView; ?></div>
					
				</div>
			</div>
			<div class="row">
				<div class="col-12 ml-1 mb-2">
					<div><?php echo $value['popis']; ?></div>
				</div>		
			</div>
			<div class="row pridaj_comment">

				<div class="col-12">
					
					<?php 
                        if(isset($p_user)){
                        ?>
                <div class="mb-1">Moja odpoveď:</div>
				<form class="mb-2" action="<?php echo $baseurl; ?>/forum/new/<?php echo $value['id']; ?>" method="POST">
					<textarea name="odpoved_na_topic" id="editor1" cols="30" rows="10"></textarea>
					<input class="btn btn-danger mt-2 hvr-buzz" type="submit" value="Poslať">
				</form>
						<?php 
                        }
                        else{
                        	?>
                        	<div>Pre odpoveď sa prihlás</div>
                        	<?php 
                        }
                        ?>
				</div>
			</div>


       	<?php
       	} 
		?>
<!-- komentare -->
		<?php 
        foreach ($reply as $value) 
		{
			 
				$time = strtotime($value['date_c']);
				$myFormatForView = date("d-m-Y H:i:s", $time);
				
       	?>
			<div class="row ml-1 jeden_reply negramot">
				<div class="col-md-1 mt-1">
					<img class="user_img_forum hvr-grow" src="<?php echo $baseurl."/img/users/".$value["img"]; ?>" alt="">
					
				</div>
				<div class="col-11 mt-1">
					<div class="user_meno hvr-grow"> <?php echo $value['meno']; ?></div>
					<br>
					<div class=" hvr-skew time"><?php echo $myFormatForView; ?></div>
				</div>
		
				<div class="answer"> <?php echo $value['answer']; ?></div>
			</div>


       	<?php
       	} 
		?>



	
	
</div>
<?php include 'inc/footer.phtml' ?>