<?php include 'inc/header.phtml' ?>
<?php $row = (isset($p_user[0]) ? $p_user[0] : ''); ?>
<div class="container pt-2">
	<div class="row">
		<div class="col-1 mr-0 pr-0">
			<img class="" style="width: 60px; height: 60px;" src="<?php echo $baseurl."/img/users/".$p_user[0]["img"]; ?>" alt="">
		</div>
		<div class="col-11 ml-0 pl-0">
			<div class="row">
				<div class="col-6">
					<div>Dátum registrácie</div>
			<div><?php echo $row['date_c']; ?></div>
				</div>
				<div class="col-6 zmena-hesla">
					<a href="<?php echo $baseurl; ?>/user/heslo/<?php echo $row['id']; ?>"><button type="button"  class="btn btn-outline-info">Zmeniť heslo</button></a>
				</div>
			</div>
			
			
			<form action="<?php echo $baseurl; ?>/user/save/<?php echo (isset($p_user[0]) ? $row['id'] : ''); ?>" method="post" enctype="multipart/form-data">

				<input type="hidden" name="id" value="<?php echo (isset($p_user[0]) ? $row['id'] : '');  ?>"><br>

				
				<label>Meno/Nick</label>
				<input type="text" class="form-control" name="meno" value="<?php echo (isset($p_user[0]) ? $row['meno'] : ''); ?>"><br>

				<label>Svoje foto (60*60)</label>
				<input type="file" name="img" class="form-control">
				<input class="btn btn-danger mt-2" type="submit" value="Upraviť profil">

			</form>
			
		</div>
	</div>
</div>
