<div class="push"></div>
</div>
<footer class="w-100 p-2 footer">Pavol Galčík © || 2019-2020</footer>

</body>
		<!--
		<script src="https://cdn.tiny.cloud/1/t11sl89c1k9g4xtvqsmg0ggop6aro4g3pwa2oreseszl2w6j/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>      
       <script>tinymce.init({selector:'textarea'});</script>
		-->
		 
		<script src="//cdn.ckeditor.com/4.13.1/basic/ckeditor.js"></script>

				<script>
                        CKEDITOR.replace( 'editor1' );
                </script>
		<script src="<?php echo $baseurl; ?>/js/wow.min.js"></script>
		<script>
              new WOW().init();
        </script>

		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</html>