<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Mono&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Asap|Comfortaa|Major+Mono+Display|Source+Code+Pro&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="<?php echo $baseurl; ?>/fonts/icomoon/style.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	    
        <link rel="stylesheet" href="<?php echo $baseurl; ?>/css/hover-min.css">

        <link rel="stylesheet" href="<?php echo $baseurl; ?>/css/animate.css">
        <link rel="stylesheet" href="<?php echo $baseurl; ?>/css/style-hlavny.css">
        

        <title>Ghydeout</title>
        
    </head>
    <body>
        
        <div class="container-fluid p-0 m-0 wrapper">
            <div class="cele_menu ">
        		<div class="row bg-dark top_menu p-0 m-0">
        			<div class="col-sm-7 logo_padding animated bounceInDown delay-1s">
                        <a style="text-decoration: none;" href="<?php echo $baseurl; ?>/domov">
                            <h1 class="logo">
                                <span class="g-menu">G</span>
                                <span style="color: white;">hyde</span>
                                <span class="out-menu">out</span>
                            </h1>
                        </a>
        				
        			</div>
        			
        			<div class="col-2 user animated bounceInRight">
                        <?php 
                        if(isset($p_user)){
                        ?>
                        <img class="user_img" src="<?php echo $baseurl."/img/users/".$p_user[0]["img"]; ?>" alt="">
                <a href="<?php echo $baseurl; ?>/user/<?php echo $p_user[0]["id"]; ?>"><?php echo $p_user[0]['meno']; ?></a>
                        <?php 
                        }
                        else
                        {
                            ?>
                            <a class="log_in" href="<?php echo $baseurl; ?>/login">
                                <span class="icon-user"></span> 
                                Prihlásiť sa
                            </a>
                            <?php 
                        }
                        ?>
        			</div>
                    <div class="col-3 log_out animated bounceInRight">
                        <?php 
                        if(isset($p_user)){
                        ?>
                        <a class="" href="<?php echo $baseurl; ?>/logout"><span class="icon-switch"></span> odhlásiť</a>
                        <?php 
                        }
                        ?>
                    </div>
        		</div>
                
        		
                   <div class="row p-0 m-0">
        			<div class="col-12 p-0 m-0">
            			<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
            				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                			<span class="navbar-toggler-icon"></span>
              				</button>

            				  <div class="collapse navbar-collapse justify-content-center menu" id="navbarNav">
            				    <ul class="navbar-nav ">
            				    	<?php 
            				    	foreach ($rows as $value) 
            				    	{
            				    		?>
            				    		<li class="nav-item hvr-overline-from-center">
            				        	<a class="nav-link" href="<?php echo $baseurl; ?>/<?php echo $value['p_menu']; ?>"><?php echo $value['p_menu'] ?></a>
            				      		</li>
            				    		<?php
            				    	} 
            				    	?>
            				      

            				    </ul>
            				  </div>
        				</nav>
        			</div>
                    <!--
                    
                    <ul class="nav justify-content-center bg-dark menu">
                        <?php 
                         foreach ($rows as $value) 
                            {
                        ?>
                      <li class="nav-item">
                        <a class="nav-link" href="<?php echo $baseurl; ?>/<?php echo $value['p_menu']; ?>"><?php echo $value['p_menu'] ?></a>
                      </li>
                      <?php
                            } 
                         ?>
                    </ul>

                    -->
                </div>
            </div>

    	